resource_types:

- name: npm
  type: docker-image
  source:
    repository: nolan/concourse-npm-resource

- name: pull-request
  type: docker-image
  source:
    repository: jtarchie/pr

resources:

- name: repo
  type: git
  source:
    uri: https://github.com/ndarilek/node-janus
    branch: master

- name: pull-requests
  type: pull-request
  source:
    access_token: {{github_access_token}}
    repo: ndarilek/node-janus

- name: package
  type: npm
  source:
    username: {{npm_username}}
    password: {{npm_password}}
    email: {{npm_email}}

jobs:

- name: release
  public: true
  plan:

  - get: repo
  - put: package
    params:
      path: repo
